# -*- coding: utf-8 -*-
"""ocr_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HdrSyX8Fu4OmisXntw1BEomPA42GGCvn
"""

# =============================================================================
#  OUTSTANDING CLAIMS RESERVE (OCR) ENGINE
#  Groups claims data by selected columns and sums numeric values.
#  African Actuarial Consultants
# =============================================================================

import pandas as pd
import numpy as np


def clean_numeric(series):
    """
    Convert problematic numeric strings to numbers.
    Handles currency symbols, parentheses for negatives, and commas.
    """
    if series.dtype == 'object':
        cleaned = series.astype(str).str.replace(r'[$,€£]', '', regex=True)
        cleaned = cleaned.str.replace(r',', '', regex=False)
        cleaned = cleaned.str.replace(r'^\((.+)\)$', r'-\1', regex=True)
        cleaned = cleaned.str.strip()
        cleaned = cleaned.replace('', np.nan)
        return pd.to_numeric(cleaned, errors='coerce')
    else:
        return pd.to_numeric(series, errors='coerce')


def calculate_ocr(df, grouping_cols, value_cols, clean_data=True):
    """
    Calculate Outstanding Claims Reserve (OCR) by grouping and summing.

    Parameters:
    -----------
    df : pd.DataFrame
        The raw claims data.
    grouping_cols : list
        List of column names to group by (e.g., ['Line_of_Business']).
    value_cols : list
        List of numeric column names to sum (e.g., ['Case_Reserve', 'Paid_Claims']).
    clean_data : bool
        Whether to run the cleaning/numeric conversion process on the data.

    Returns:
    --------
    results_df : pd.DataFrame
        Grouped results with a TOTAL row appended.
    cleaning_report : dict
        Dictionary containing cleaning statistics (duplicates removed, conversion issues).
    """

    # Work on a copy to avoid modifying the original dataframe
    df_processed = df.copy()
    cleaning_report = {
        'original_rows': len(df_processed),
        'duplicates_removed': 0,
        'conversion_issues': []
    }

    # Step 1: Data Cleaning (if requested)
    if clean_data:
        # Check for missing values in selected columns
        all_selected_cols = grouping_cols + value_cols
        missing_in_selected = False
        for col in all_selected_cols:
            if df_processed[col].isna().sum() > 0:
                # Just warn but don't stop; we can handle missing values in grouping
                pass

        # Remove duplicates
        duplicate_count = df_processed.duplicated().sum()
        if duplicate_count > 0:
            df_processed = df_processed.drop_duplicates()
            cleaning_report['duplicates_removed'] = duplicate_count

        # Check and convert non-numeric values
        for col in value_cols:
            test_conversion = clean_numeric(df_processed[col])
            failed_mask = test_conversion.isna() & df_processed[col].notna()
            failed_count = failed_mask.sum()
            if failed_count > 0:
                problematic = df_processed[col][failed_mask].head(3).tolist()
                cleaning_report['conversion_issues'].append({
                    'column': col,
                    'failed_count': failed_count,
                    'examples': problematic
                })
                # Apply cleaning
                df_processed[col] = clean_numeric(df_processed[col])
                df_processed[col] = df_processed[col].fillna(0)
            else:
                df_processed[col] = pd.to_numeric(df_processed[col], errors='coerce').fillna(0)

    # Step 2: Group and Sum
    df_grouped = df_processed.groupby(grouping_cols)[value_cols].sum().reset_index()

    # Step 3: Add TOTAL row
    total_row = {}
    for col in grouping_cols:
        total_row[col] = "TOTAL"
    for col in value_cols:
        total_row[col] = df_grouped[col].sum()

    results_df = pd.concat([df_grouped, pd.DataFrame([total_row])], ignore_index=True)

    # Step 4: Calculate Grand Total
    grand_total = sum(df_grouped[col].sum() for col in value_cols)

    return results_df, cleaning_report, grand_total
