# -*- coding: utf-8 -*-
"""npr_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14F65UnYCMCV2Bt05n3GnDPywqrt4PYAh
"""

# =============================================================================
#  REINSURANCE NON-PERFORMANCE RISK (NPR) ENGINE
#  IFRS 17 Para 63(e) — Credit risk adjustment on reinsurance held
#  Formula: NPR = PD × Reinsurer Share × Ceded LIC (IBNR + OCR)
#  RA is EXCLUDED from the LIC base.
# =============================================================================

import pandas as pd
import numpy as np


def calculate_npr_aggregation(df_ri, df_lic):
    """
    Aggregation basis:
      NPR per reinsurer per portfolio = Overall_Share × Total_Ceded_LIC × PD

    Parameters:
    -----------
    df_ri : pd.DataFrame
        Must contain columns: 'Reinsurer_Name', 'Credit_Rating', 'PD', 'Overall_Share'.
    df_lic : pd.DataFrame
        Must contain columns: 'Portfolio', 'Total_Ceded_LIC'.

    Returns:
    --------
    detail_df : pd.DataFrame
        NPR details per portfolio per reinsurer.
    by_portfolio_df : pd.DataFrame
        NPR summed by Portfolio.
    by_reinsurer_df : pd.DataFrame
        NPR summed by Reinsurer.
    total_npr : float
        Total NPR across all portfolios and reinsurers.
    """
    rows = []
    for _, ri_row in df_ri.iterrows():
        for _, lic_row in df_lic.iterrows():
            npr = ri_row["Overall_Share"] * lic_row["Total_Ceded_LIC"] * ri_row["PD"]
            rows.append({
                "Portfolio":       lic_row["Portfolio"],
                "Reinsurer":       ri_row["Reinsurer_Name"],
                "Credit_Rating":   ri_row["Credit_Rating"],
                "PD":              ri_row["PD"],
                "Overall_Share":   ri_row["Overall_Share"],
                "Total_Ceded_LIC": lic_row["Total_Ceded_LIC"],
                "Ceded_IBNR":      lic_row.get("Ceded_IBNR", np.nan),
                "Ceded_OCR":       lic_row.get("Ceded_OCR", np.nan),
                "NPR":             npr,
            })

    detail = pd.DataFrame(rows)
    by_portfolio = detail.groupby("Portfolio")["NPR"].sum().reset_index()
    by_reinsurer = detail.groupby("Reinsurer")["NPR"].sum().reset_index()
    total_npr = detail["NPR"].sum()

    return detail, by_portfolio, by_reinsurer, total_npr


def calculate_npr_per_portfolio(df_ri, df_lic, portfolios):
    """
    Per-portfolio basis:
      NPR = Share_for_that_portfolio × Total_Ceded_LIC × PD

    Parameters:
    -----------
    df_ri : pd.DataFrame
        Must contain columns: 'Reinsurer_Name', 'Credit_Rating', 'PD',
        plus one column per portfolio name containing the share for that portfolio.
    df_lic : pd.DataFrame
        Must contain columns: 'Portfolio', 'Total_Ceded_LIC'.
    portfolios : list
        List of portfolio names (used to look up the correct share column).

    Returns:
    --------
    detail_df : pd.DataFrame
        NPR details per portfolio per reinsurer.
    by_portfolio_df : pd.DataFrame
        NPR summed by Portfolio.
    by_reinsurer_df : pd.DataFrame
        NPR summed by Reinsurer.
    total_npr : float
        Total NPR across all portfolios and reinsurers.
    """
    rows = []
    for _, ri_row in df_ri.iterrows():
        for _, lic_row in df_lic.iterrows():
            portfolio = lic_row["Portfolio"]
            # Look up the share column for this portfolio
            share = ri_row.get(portfolio, np.nan)
            if pd.isna(share):
                # If column doesn't exist, treat as 0 and warn (handled in UI)
                share = 0.0

            npr = share * lic_row["Total_Ceded_LIC"] * ri_row["PD"]
            rows.append({
                "Portfolio":        portfolio,
                "Reinsurer":        ri_row["Reinsurer_Name"],
                "Credit_Rating":    ri_row["Credit_Rating"],
                "PD":               ri_row["PD"],
                "Portfolio_Share":  share,
                "Total_Ceded_LIC":  lic_row["Total_Ceded_LIC"],
                "Ceded_IBNR":       lic_row.get("Ceded_IBNR", np.nan),
                "Ceded_OCR":        lic_row.get("Ceded_OCR", np.nan),
                "NPR":              npr,
            })

    detail = pd.DataFrame(rows)
    by_portfolio = detail.groupby("Portfolio")["NPR"].sum().reset_index()
    by_reinsurer = detail.groupby("Reinsurer")["NPR"].sum().reset_index()
    total_npr = detail["NPR"].sum()

    return detail, by_portfolio, by_reinsurer, total_npr
