# -*- coding: utf-8 -*-
"""full_LRC_IFRS17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/193q960sUOkvScsOoERZBLaYh2pLGbQwA
"""

# =============================================================================
#  FULL IFRS 17 LRC (PAA) ENGINE
#  Pure calculation engine — completely independent of UI
#  Location: /Full Valuation/full_LRC_IFRS17.py
# =============================================================================

import pandas as pd
import numpy as np


def calculate_full_ifrs17_lrc(
    opening_balances_df,
    cashflows_df,
    policy_df,
    loss_component_df,
    yield_curve_df,
    claims_curve_df,
    config,
    valuation_date
):
    """
    Full IFRS 17 LRC (PAA) Engine.

    Parameters
    ----------
    opening_balances_df : pd.DataFrame
        Columns: Group, Opening_LRC_Excl_Loss, Opening_Loss_Component
    cashflows_df : pd.DataFrame
        Columns: Group, Premiums_Received, IACF_Paid, Investment_Components_Paid
    policy_df : pd.DataFrame
        Columns: Group, Start_Date, End_Date, Written_Premium
    loss_component_df : pd.DataFrame
        Columns: Group, Expected_Future_Premiums, Loss_Ratio, Commission_Ratio,
                 Expense_Ratio, RA_Ratio
    yield_curve_df : pd.DataFrame or None
        Columns: Duration_Years, Spot_Rate
    claims_curve_df : pd.DataFrame or None
        Columns: Period, Percentage
    config : dict
        {
            'iacf_toggle': "Expense Immediately" or "Capitalize & Amortize",
            'discount_toggle': "No Discounting" or "Apply Discounting",
            'invest_toggle': "No" or "Yes",
            'revenue_toggle': "Passage of Time" or "Emergence of Risk"
        }
    valuation_date : date or datetime

    Returns
    -------
    results : dict
        Per-group LRC roll-forward results.
    """
    val_date = pd.to_datetime(valuation_date)
    results = {}

    # ---- Pre-process Policy Data ----
    policy_df = policy_df.copy()
    policy_df['Start_Date'] = pd.to_datetime(policy_df['Start_Date'], errors='coerce')
    policy_df['End_Date'] = pd.to_datetime(policy_df['End_Date'], errors='coerce')
    policy_df = policy_df.dropna(subset=['Start_Date', 'End_Date'])
    policy_df = policy_df[policy_df['End_Date'] > policy_df['Start_Date']]
    policy_df['Written_Premium'] = pd.to_numeric(policy_df['Written_Premium'], errors='coerce')

    policy_df['Policy_Days'] = (policy_df['End_Date'] - policy_df['Start_Date']).dt.days
    policy_df['Passed_Days'] = (val_date - policy_df['Start_Date']).dt.days
    policy_df['Passed_Days'] = np.clip(policy_df['Passed_Days'], 0, policy_df['Policy_Days'])
    policy_df['Remaining_Days'] = policy_df['Policy_Days'] - policy_df['Passed_Days']
    policy_df['UPR'] = policy_df['Written_Premium'] * (policy_df['Remaining_Days'] / policy_df['Policy_Days'])

    groups = policy_df['Group'].dropna().unique().tolist()

    # ---- Per-Group Calculation ----
    for group in groups:
        grp_policies = policy_df[policy_df['Group'] == group]

        grp_cf = cashflows_df[cashflows_df['Group'] == group] if cashflows_df is not None else pd.DataFrame()
        grp_ob = opening_balances_df[opening_balances_df['Group'] == group] if opening_balances_df is not None else pd.DataFrame()
        grp_lc = loss_component_df[loss_component_df['Group'] == group] if loss_component_df is not None else pd.DataFrame()

        # 1. Opening Balances
        opening_lrc_excl_loss = float(grp_ob['Opening_LRC_Excl_Loss'].values[0]) if not grp_ob.empty else 0.0
        opening_loss_component = float(grp_ob['Opening_Loss_Component'].values[0]) if not grp_ob.empty else 0.0

        # 2. Cashflows
        premiums_received = float(grp_cf['Premiums_Received'].values[0]) if not grp_cf.empty else 0.0
        iacf_paid_raw = float(grp_cf['IACF_Paid'].values[0]) if not grp_cf.empty else 0.0
        investment_components_paid = float(grp_cf['Investment_Components_Paid'].values[0]) if not grp_cf.empty else 0.0
        iacf_paid = iacf_paid_raw if config['iacf_toggle'] == "Capitalize & Amortize" else 0.0

        # 3. Weighted Average Duration
        grp_policies['Duration_Years'] = grp_policies['Policy_Days'] / 365.25
        total_wp = grp_policies['Written_Premium'].sum()
        weighted_duration = np.average(grp_policies['Duration_Years'], weights=grp_policies['Written_Premium']) if total_wp > 0 else 0.0
        locked_in_years = max(1, int(np.ceil(weighted_duration))) if weighted_duration > 0 else 1

        # 4. Allocation Factor & Insurance Revenue
        total_written_premium = total_wp
        total_policy_days = grp_policies['Policy_Days'].sum()
        total_passed_days = grp_policies['Passed_Days'].sum()

        if config['revenue_toggle'] == "Passage of Time":
            allocation_factor = (total_passed_days / total_policy_days) if total_policy_days > 0 else 0.0
            allocated_premium = total_written_premium * allocation_factor
        else:  # Emergence of Risk
            claims_curve = claims_curve_df
            allocation_factor = float(claims_curve['Percentage'].sum()) if claims_curve is not None and not claims_curve.empty else 0.0
            allocated_premium = total_written_premium * allocation_factor

        # Investment Components Allocated (simplified for this version)
        total_investment_components = 0.0
        allocated_investment_components = total_investment_components * allocation_factor

        # 5. Financing Adjustment
        locked_in_rate = 0.0
        if config['discount_toggle'] == "Apply Discounting" and yield_curve_df is not None:
            yc_years = yield_curve_df['Duration_Years'].values
            yc_rates = yield_curve_df['Spot_Rate'].values
            if locked_in_years in yc_years:
                locked_in_rate = float(yc_rates[np.where(yc_years == locked_in_years)[0][0]])
            else:
                locked_in_rate = float(np.interp(locked_in_years, yc_years, yc_rates, left=yc_rates[0], right=yc_rates[-1]))

        financing_adjustment = opening_lrc_excl_loss * locked_in_rate

        # 6. Insurance Revenue
        insurance_revenue = (allocated_premium - allocated_investment_components) + financing_adjustment

        # 7. IACF Amortisation
        iacf_amortized = (iacf_paid * allocation_factor) if config['iacf_toggle'] == "Capitalize & Amortize" else 0.0

        # 8. Loss Component
        if not grp_lc.empty:
            expected_future_premiums = float(grp_lc['Expected_Future_Premiums'].values[0])
            loss_ratio = float(grp_lc['Loss_Ratio'].values[0])
            commission_ratio = float(grp_lc['Commission_Ratio'].values[0])
            expense_ratio = float(grp_lc['Expense_Ratio'].values[0])
            ra_ratio = float(grp_lc['RA_Ratio'].values[0])
            combined_ratio = loss_ratio + commission_ratio + expense_ratio + ra_ratio
            closing_loss_component = expected_future_premiums * max(0.0, combined_ratio - 1.0)
        else:
            closing_loss_component = 0.0

        # 9. Loss Reversals / New Losses
        loss_reversals = min(opening_loss_component, max(allocated_premium, 0.0))
        new_losses_arising = closing_loss_component - opening_loss_component + loss_reversals

        # 10. Closing LRC
        closing_lrc_excl_loss = (
            opening_lrc_excl_loss
            + premiums_received
            - insurance_revenue
            - iacf_paid
            + iacf_amortized
            + financing_adjustment
            - investment_components_paid
        )
        total_closing_lrc = closing_lrc_excl_loss + closing_loss_component

        # 11. Store Results
        results[group] = {
            'Opening_LRC_Excl_Loss': opening_lrc_excl_loss,
            'Opening_Loss_Component': opening_loss_component,
            'Premiums_Received': premiums_received,
            'Allocated_Premium': allocated_premium,
            'Allocated_Investment_Components': allocated_investment_components,
            'Insurance_Revenue': insurance_revenue,
            'IACF_Paid': iacf_paid,
            'IACF_Amortized': iacf_amortized,
            'Financing_Adjustment': financing_adjustment,
            'Locked_In_Rate': locked_in_rate,
            'Locked_In_Years': locked_in_years,
            'Investment_Components_Paid': investment_components_paid,
            'Loss_Ratio': loss_ratio,
            'Commission_Ratio': commission_ratio,
            'Expense_Ratio': expense_ratio,
            'RA_Ratio': ra_ratio,
            'Combined_Ratio': combined_ratio,
            'Expected_Future_Premiums': expected_future_premiums,
            'Loss_Reversals': loss_reversals,
            'New_Losses_Arising': new_losses_arising,
            'Closing_LRC_Excl_Loss': closing_lrc_excl_loss,
            'Closing_Loss_Component': closing_loss_component,
            'Total_Closing_LRC': total_closing_lrc,
            'UPR_Snapshot': grp_policies['UPR'].sum(),
        }

    return results
