# -*- coding: utf-8 -*-
"""ulae_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RfkxD3ACtNHmkbLV052KkaI2uAIrnJRJ
"""

# =============================================================================
#  ULAE (UNALLOCATED LOSS ADJUSTMENT EXPENSES) ENGINE
#  Formula: ULAE = ULAE_Ratio × (50% × OCR + IBNR)
#  Supports: Per Portfolio or Aggregated (Apportioned) basis
# =============================================================================

import pandas as pd
import numpy as np


def calculate_ulae_per_portfolio(df_reserves, ulae_ratios, is_detailed=True):
    """
    Calculate ULAE separately for each portfolio.

    Parameters:
    -----------
    df_reserves : pd.DataFrame
        Must contain columns: 'Portfolio', and either ('OCR', 'IBNR') or 'Total_Reserves'.
    ulae_ratios : dict
        Dictionary mapping Portfolio names to ULAE ratios (e.g., {'Motor': 0.05}).
    is_detailed : bool
        True if df_reserves has 'OCR' and 'IBNR' columns. False if it has 'Total_Reserves'.

    Returns:
    --------
    results_df : pd.DataFrame
        DataFrame with ULAE calculated per portfolio.
    """
    results = df_reserves.copy()

    # Map ratios to portfolios
    results['ULAE_Ratio'] = results['Portfolio'].map(ulae_ratios).fillna(0.0)

    # Calculate ULAE Base
    if is_detailed:
        results['ULAE_Base'] = 0.5 * results['OCR'] + results['IBNR']
    else:
        results['ULAE_Base'] = results['Total_Reserves']

    # Calculate ULAE
    results['ULAE'] = results['ULAE_Ratio'] * results['ULAE_Base']

    return results[['Portfolio', 'OCR', 'IBNR', 'Total_Reserves', 'ULAE_Ratio', 'ULAE_Base', 'ULAE']]


def calculate_ulae_aggregated(df_reserves, ulae_ratio, apportionment_df, is_detailed=True):
    """
    Calculate ULAE on an aggregated basis, then apportion to portfolios.

    Parameters:
    -----------
    df_reserves : pd.DataFrame
        Must contain columns: 'Portfolio', and either ('OCR', 'IBNR') or 'Total_Reserves'.
    ulae_ratio : float
        The single ULAE ratio to apply to the total base (e.g., 0.05).
    apportionment_df : pd.DataFrame
        Must contain columns: 'Portfolio' and 'Apportionment_Pct' (sums to 1.0).
    is_detailed : bool
        True if df_reserves has 'OCR' and 'IBNR' columns. False if it has 'Total_Reserves'.

    Returns:
    --------
    results_df : pd.DataFrame
        DataFrame with ULAE calculated and apportioned.
    total_ulae_base : float
        The total ULAE base used for the calculation.
    """
    results = df_reserves.copy()

    # Calculate total ULAE Base
    if is_detailed:
        total_ulae_base = (0.5 * results['OCR'] + results['IBNR']).sum()
        results['ULAE_Base'] = 0.5 * results['OCR'] + results['IBNR']
    else:
        total_ulae_base = results['Total_Reserves'].sum()
        results['ULAE_Base'] = results['Total_Reserves']

    # Calculate total ULAE
    total_ulae = total_ulae_base * ulae_ratio

    # Merge apportionment percentages
    results = results.merge(
        apportionment_df[['Portfolio', 'Apportionment_Pct']],
        on='Portfolio', how='left'
    )
    results['Apportionment_Pct'] = results['Apportionment_Pct'].fillna(0.0)

    # Apportion ULAE
    results['ULAE'] = total_ulae * results['Apportionment_Pct']
    results['ULAE_Ratio'] = ulae_ratio

    return results[['Portfolio', 'OCR', 'IBNR', 'Total_Reserves', 'ULAE_Ratio', 'ULAE_Base', 'ULAE', 'Apportionment_Pct']], total_ulae_base


def calculate_apportionment_percentages(apportionment_df):
    """
    Calculate apportionment percentages from an amount column.

    Parameters:
    -----------
    apportionment_df : pd.DataFrame
        Must contain columns: 'Portfolio' and 'Amount'.

    Returns:
    --------
    apportionment_df : pd.DataFrame
        The input DataFrame with an added 'Apportionment_Pct' column.
    """
    total_amount = apportionment_df['Amount'].sum()
    if total_amount > 0:
        apportionment_df['Apportionment_Pct'] = apportionment_df['Amount'] / total_amount
    else:
        apportionment_df['Apportionment_Pct'] = 0.0
    return apportionment_df
