# -*- coding: utf-8 -*-
"""loss_component_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TAxWFyJ17LxjuEFOANTOnqWmG8aKaJ9O
"""

# =============================================================================
#  LOSS COMPONENT ENGINE – IFRS 17 PAA
#  Pure calculation engine for the Loss Component (Onerous Contracts)
#  Formula: Loss Component = Max(0, Combined Ratio − 1) × Closing UPR
# =============================================================================

import pandas as pd
import numpy as np


def calculate_loss_component(
    df: pd.DataFrame,
    lob_col: str,
    written_premium_col: str,
    expenses_col: str,
    commission_col: str,
    paid_claims_col: str,
    opening_ocr_col: str,
    closing_ocr_col: str,
    opening_ibnr_col: str,
    closing_ibnr_col: str,
    opening_upr_col: str,
    closing_upr_col: str,
    risk_adjustment_col: str,
) -> pd.DataFrame:
    """
    Calculate the IFRS 17 Loss Component per Line of Business.

    Parameters
    ----------
    df : pd.DataFrame
        Raw input data (one row per portfolio/LOB).
    lob_col : str
        Column name for Line of Business.
    written_premium_col : str
        Gross written premiums.
    expenses_col : str
        Gross attributable expenses.
    commission_col : str
        Gross commission paid.
    paid_claims_col : str
        Gross paid claims during the period.
    opening_ocr_col : str
        Opening outstanding claims reserve.
    closing_ocr_col : str
        Closing outstanding claims reserve.
    opening_ibnr_col : str
        Opening IBNR reserve.
    closing_ibnr_col : str
        Closing IBNR reserve.
    opening_upr_col : str
        Opening unearned premium reserve.
    closing_upr_col : str
        Closing unearned premium reserve.
    risk_adjustment_col : str
        Gross risk adjustment amount.

    Returns
    -------
    result : pd.DataFrame
        Aggregated results by Line of Business with all ratios and the Loss Component.
    """
    # 1. Work on a copy
    df_work = df.copy()

    # 2. Ensure numeric conversion
    numeric_cols = [
        written_premium_col, expenses_col, commission_col, paid_claims_col,
        opening_ocr_col, closing_ocr_col, opening_ibnr_col, closing_ibnr_col,
        opening_upr_col, closing_upr_col, risk_adjustment_col
    ]
    for col in numeric_cols:
        df_work[col] = pd.to_numeric(df_work[col], errors='coerce').fillna(0)

    # 3. Derived intermediates
    df_work['Actual_Incurred_Claims'] = (
        df_work[paid_claims_col]
        + df_work[closing_ibnr_col]
        + df_work[closing_ocr_col]
        - df_work[opening_ibnr_col]
        - df_work[opening_ocr_col]
    )

    df_work['Earned_Premiums'] = (
        df_work[written_premium_col]
        + df_work[opening_upr_col]
        - df_work[closing_upr_col]
    )

    # 4. Aggregate by Line of Business
    result = df_work.groupby(lob_col).agg(
        Total_Written_Premiums   =(written_premium_col, 'sum'),
        Total_Earned_Premiums    =('Earned_Premiums', 'sum'),
        Total_Incurred_Claims    =('Actual_Incurred_Claims', 'sum'),
        Total_Commission_Paid    =(commission_col, 'sum'),
        Total_Expenses           =(expenses_col, 'sum'),
        Total_Risk_Adjustment    =(risk_adjustment_col, 'sum'),
        Closing_IBNR             =(closing_ibnr_col, 'sum'),
        Closing_OCR              =(closing_ocr_col, 'sum'),
        Closing_UPR              =(closing_upr_col, 'sum'),
    ).reset_index()

    # 5. Calculate Ratios
    result['Loss_Ratio'] = np.where(
        result['Total_Earned_Premiums'] != 0,
        result['Total_Incurred_Claims'] / result['Total_Earned_Premiums'],
        np.nan,
    )

    result['Commission_Ratio'] = np.where(
        result['Total_Written_Premiums'] != 0,
        result['Total_Commission_Paid'] / result['Total_Written_Premiums'],
        np.nan,
    )

    result['Expense_Ratio'] = np.where(
        result['Total_Written_Premiums'] != 0,
        result['Total_Expenses'] / result['Total_Written_Premiums'],
        np.nan,
    )

    risk_denom = result['Closing_IBNR'] + result['Closing_OCR']
    result['Risk_Adjustment_Ratio'] = np.where(
        risk_denom != 0,
        result['Total_Risk_Adjustment'] / risk_denom,
        np.nan,
    )

    result['Combined_Ratio'] = (
        result['Loss_Ratio']
        + result['Commission_Ratio']
        + result['Expense_Ratio']
        + result['Risk_Adjustment_Ratio']
    )

    # 6. Loss Component
    result['Loss_Component'] = (
        np.maximum(result['Combined_Ratio'] - 1, 0) * result['Closing_UPR']
    )

    return result
