# -*- coding: utf-8 -*-
"""upr_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLE_RjwQ3jsrJXFq6QTUP5K-oMmXdjkY
"""

# =============================================================================
#  UPR ENGINE – LIABILITY FOR REMAINING COVERAGE
#  Pure calculation engine for Unearned Premium Reserve (UPR)
#  Supports: 365th, 24th, 8th methods
#  Duration & Remaining days use inclusive day-count (End - Start + 1)
# =============================================================================

import pandas as pd
import numpy as np


def calculate_upr(
    df: pd.DataFrame,
    start_date_col: str,
    end_date_col: str,
    value_cols: list,
    grouping_cols: list,
    valuation_date: pd.Timestamp,
    method: str
) -> pd.DataFrame:
    """
    Calculate Unearned Premium Reserve (UPR).

    Parameters
    ----------
    df : pd.DataFrame
        Raw policy data.
    start_date_col : str
        Column name for policy start date.
    end_date_col : str
        Column name for policy end date.
    value_cols : list
        List of numeric column names to apply UPR to (e.g., ['Gross_Written_Premium']).
    grouping_cols : list
        List of column names to group by (e.g., ['Line_of_Business']).
    valuation_date : pd.Timestamp
        The valuation date.
    method : str
        '365th', '24th', or '8th'

    Returns
    -------
    result : pd.DataFrame
        Grouped UPR results. Column names are the original value_cols (no _UPR suffix).
    """
    # 1. Prepare working copy
    df_work = df.copy()
    df_work['Start_Date'] = pd.to_datetime(df_work[start_date_col], errors='coerce')
    df_work['End_Date']   = pd.to_datetime(df_work[end_date_col], errors='coerce')

    # 2. Filter out invalid dates
    df_work = df_work.dropna(subset=['Start_Date', 'End_Date'])
    df_work = df_work[df_work['End_Date'] > df_work['Start_Date']]

    # 3. Convert value columns to numeric
    for col in value_cols:
        df_work[col] = pd.to_numeric(df_work[col], errors='coerce')

    # 4. Calculate Duration and Remaining Days (INCLUSIVE: +1)
    df_work['Duration_Days'] = (df_work['End_Date'] - df_work['Start_Date']).dt.days + 1
    df_work['Remaining_Days'] = (df_work['End_Date'] - valuation_date).dt.days + 1

    # 5. Clamp Remaining_Days to [0, Duration_Days]
    df_work['Remaining_Days'] = np.clip(df_work['Remaining_Days'], 0, df_work['Duration_Days'])

    # 6. Calculate Unearned Portion
    if method == '365th':
        # Exact days
        df_work['Unearned_Portion'] = df_work['Remaining_Days'] / df_work['Duration_Days']

    elif method == '24th':
        # Half-month approximation
        interval = 365.25 / 24
        df_work['Unearned_Portion'] = (df_work['Remaining_Days'] / interval) / (df_work['Duration_Days'] / interval)

    elif method == '8th':
        # Half-quarter approximation
        interval = 365.25 / 8
        df_work['Unearned_Portion'] = (df_work['Remaining_Days'] / interval) / (df_work['Duration_Days'] / interval)

    else:
        raise ValueError(f"Unknown method: {method}")

    # 7. Apply UPR to each value column
    upr_cols = []
    for col in value_cols:
        upr_col = f'{col}_UPR'
        df_work[upr_col] = df_work['Unearned_Portion'] * df_work[col]
        upr_cols.append(upr_col)

    # 8. Group and sum
    result = df_work.groupby(grouping_cols)[upr_cols].sum().reset_index()

    # 9. Rename columns back to original names (strip _UPR suffix)
    result.columns = grouping_cols + value_cols

    return result