# -*- coding: utf-8 -*-
"""actuarial_helpers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hnd4wsaomcfwa1F49E1LBlEb4bUEJHHm
"""

# =============================================================================
#  ACTUARIAL HELPERS
#  Shared mathematical utilities for BCL, Cape Cod, BF, Mack & Bootstrap
#  Tail factor hardcoded to 1.000 (fully developed) in respective engines.
# =============================================================================

import pandas as pd
import numpy as np
from scipy import interpolate, stats


# =============================================================================
#  1. PERIOD UTILITIES
# =============================================================================

def periods_per_year(grain):
    return {"Y": 1, "H": 2, "Q": 4, "M": 12}[grain]

def period_index(dt, origin, grain):
    if grain == "Y": return dt.year - origin.year
    elif grain == "H":
        oy = origin.year * 2 + (0 if origin.month <= 6 else 1)
        dy = dt.year * 2 + (0 if dt.month <= 6 else 1)
        return dy - oy
    elif grain == "Q":
        oq = origin.year * 4 + (origin.month - 1) // 3
        dq = dt.year * 4 + (dt.month - 1) // 3
        return dq - oq
    elif grain == "M":
        return (dt.year - origin.year) * 12 + (dt.month - origin.month)

def period_label(idx, origin, grain):
    if grain == "Y": return str(origin.year + idx)
    elif grain == "H":
        base = origin.year * 2 + (0 if origin.month <= 6 else 1) + idx
        y, h = base // 2, base % 2 + 1
        return f"{y}-H{h}"
    elif grain == "Q":
        base = origin.year * 4 + (origin.month - 1) // 3 + idx
        y, q = base // 4, base % 4 + 1
        return f"{y}-Q{q}"
    elif grain == "M":
        total = origin.year * 12 + origin.month - 1 + idx
        y, m = total // 12, total % 12 + 1
        return f"{y}-{m:02d}"


# =============================================================================
#  2. TRIANGLE CONSTRUCTION
# =============================================================================

def build_triangles(df, loss_col, report_col, amount_col, origin, grain, n_periods):
    df = df.copy()
    df["__ap"] = df[loss_col].apply(lambda d: period_index(d, origin, grain))
    df["__dp"] = df.apply(
        lambda r: max(0, min(period_index(r[report_col], origin, grain) - period_index(r[loss_col], origin, grain), n_periods - 1)),
        axis=1
    )
    df = df[(df["__ap"] >= 0) & (df["__ap"] < n_periods)]
    df_valid = df.dropna(subset=[amount_col])

    if len(df_valid) > 0:
        pivot = df_valid.pivot_table(index="__ap", columns="__dp", values=amount_col, aggfunc="sum")
    else:
        pivot = pd.DataFrame(index=pd.RangeIndex(n_periods), columns=pd.RangeIndex(n_periods), dtype=float)

    for ap in range(n_periods):
        if ap not in pivot.index: pivot.loc[ap] = np.nan
    for dp in range(n_periods):
        if dp not in pivot.columns: pivot[dp] = np.nan

    inc = pivot.sort_index()[sorted(pivot.columns)].copy().astype(float)

    obs_mask = pd.DataFrame(False, index=inc.index, columns=inc.columns)
    for ap in inc.index:
        for dp in inc.columns:
            if ap + dp < n_periods:
                obs_mask.loc[ap, dp] = pd.notna(inc.loc[ap, dp])

    for ap in inc.index:
        for dp in inc.columns:
            if ap + dp >= n_periods: inc.loc[ap, dp] = np.nan

    cum = inc.copy()
    for ap in inc.index:
        has_obs = any(pd.notna(inc.loc[ap, dp]) for dp in inc.columns if ap + dp < n_periods)
        if not has_obs:
            cum.loc[ap] = np.nan
            continue
        running = 0.0
        for dp in sorted(inc.columns):
            if ap + dp < n_periods:
                v = inc.loc[ap, dp]
                running += v if pd.notna(v) else 0.0
                cum.loc[ap, dp] = running
            else:
                cum.loc[ap, dp] = np.nan
    return inc, cum, obs_mask


# =============================================================================
#  3. DEVELOPMENT FACTOR METHODS (ALL 6)
# =============================================================================

def volume_weighted_factors(cum, obs_mask=None):
    n_ap, n_dp = cum.shape
    factors = []
    for j in range(n_dp - 1):
        num, den = 0.0, 0.0
        for i in range(n_ap):
            if i + j + 1 < n_ap:
                if obs_mask is not None:
                    if not obs_mask.iloc[i, j] or not obs_mask.iloc[i, j + 1]:
                        continue
                c = cum.iloc[i, j]
                n = cum.iloc[i, j + 1]
                if pd.notna(c) and pd.notna(n) and c > 0:
                    num += n
                    den += c
        factors.append(num / den if den > 0 else 1.0)
    return factors

def simple_average_factors(cum, obs_mask=None):
    n_ap, n_dp = cum.shape
    factors = []
    for j in range(n_dp - 1):
        indiv = []
        for i in range(n_ap):
            if i + j + 1 < n_ap:
                if obs_mask is not None:
                    if not obs_mask.iloc[i, j] or not obs_mask.iloc[i, j + 1]:
                        continue
                c = cum.iloc[i, j]
                n = cum.iloc[i, j + 1]
                if pd.notna(c) and pd.notna(n) and c > 0:
                    indiv.append(n / c)
        factors.append(np.mean(indiv) if indiv else 1.0)
    return factors

def geometric_average_factors(cum, obs_mask=None):
    n_ap, n_dp = cum.shape
    factors = []
    for j in range(n_dp - 1):
        indiv = []
        for i in range(n_ap):
            if i + j + 1 < n_ap:
                if obs_mask is not None:
                    if not obs_mask.iloc[i, j] or not obs_mask.iloc[i, j + 1]:
                        continue
                c = cum.iloc[i, j]
                n = cum.iloc[i, j + 1]
                if pd.notna(c) and pd.notna(n) and c > 0:
                    indiv.append(n / c)
        factors.append(np.exp(np.mean(np.log(indiv))) if indiv else 1.0)
    return factors

def medial_average_factors(cum, obs_mask=None):
    n_ap, n_dp = cum.shape
    factors = []
    for j in range(n_dp - 1):
        indiv = []
        for i in range(n_ap):
            if i + j + 1 < n_ap:
                if obs_mask is not None:
                    if not obs_mask.iloc[i, j] or not obs_mask.iloc[i, j + 1]:
                        continue
                c = cum.iloc[i, j]
                n = cum.iloc[i, j + 1]
                if pd.notna(c) and pd.notna(n) and c > 0:
                    indiv.append(n / c)
        if len(indiv) >= 3:
            indiv_sorted = sorted(indiv)
            factors.append(np.mean(indiv_sorted[1:-1]))
        else:
            factors.append(np.mean(indiv) if indiv else 1.0)
    return factors

def linear_regression_factors(cum, obs_mask=None):
    sa = simple_average_factors(cum, obs_mask)
    x = np.array(range(1, len(sa) + 1), dtype=float)
    y = np.array(sa, dtype=float)
    slope, intercept, r, p, se = stats.linregress(x, y)
    smoothed = [max(intercept + slope * xi, 1.0) for xi in x]
    return smoothed, slope, intercept, r ** 2

def weighted_last_n_factors(cum, n=3, obs_mask=None):
    n_ap, n_dp = cum.shape
    factors = []
    for j in range(n_dp - 1):
        pairs = []
        for i in range(n_ap):
            if i + j + 1 < n_ap:
                if obs_mask is not None:
                    if not obs_mask.iloc[i, j] or not obs_mask.iloc[i, j + 1]:
                        continue
                c = cum.iloc[i, j]
                nxt = cum.iloc[i, j + 1]
                if pd.notna(c) and pd.notna(nxt) and c > 0:
                    pairs.append((c, nxt, i))
        pairs.sort(key=lambda x: x[2], reverse=True)
        pairs = pairs[:n]
        num = sum(p[1] for p in pairs)
        den = sum(p[0] for p in pairs)
        factors.append(num / den if den > 0 else 1.0)
    return factors


# =============================================================================
#  4. DIAGNOSTICS & RECOMMENDATIONS
# =============================================================================

def stability_diagnostics(cum, obs_mask=None):
    n_ap, n_dp = cum.shape
    cvs = {}
    for j in range(n_dp - 1):
        indiv = []
        for i in range(n_ap):
            if i + j + 1 < n_ap:
                if obs_mask is not None:
                    if not obs_mask.iloc[i, j] or not obs_mask.iloc[i, j + 1]:
                        continue
                c = cum.iloc[i, j]
                n = cum.iloc[i, j + 1]
                if pd.notna(c) and pd.notna(n) and c > 0:
                    indiv.append(n / c)
        if len(indiv) >= 2:
            cvs[j] = np.std(indiv, ddof=1) / np.mean(indiv) if np.mean(indiv) > 0 else 0
        else:
            cvs[j] = 0.0
    return cvs

def recommend_factors(vw, sa, geo, med, lr_tuple, cvs):
    lr, slope, intercept, r2 = lr_tuple
    mean_cv = np.mean(list(cvs.values())) if cvs else 0
    recommendations = []
    if mean_cv < 0.05:
        recommendations.append(("Volume-Weighted", "Low volatility — volume-weighted is stable and unbiased."))
    elif mean_cv < 0.15:
        recommendations.append(("Medial Average", "Moderate volatility — medial average reduces outlier influence."))
        recommendations.append(("Geometric Average", "Geometric average also appropriate for moderate volatility."))
    else:
        recommendations.append(("Linear Regression Smoothed", f"High volatility (mean CV={mean_cv:.1%}). Regression smoothing (R²={r2:.3f}) recommended."))
    if abs(slope) > 0.01 and r2 > 0.60:
        if not any("Regression" in r[0] for r in recommendations):
            recommendations.append(("Linear Regression Smoothed", f"Significant trend detected (slope={slope:.4f}, R²={r2:.3f})."))
    return recommendations, mean_cv

def compute_cdfs(factors):
    cdfs = []
    running = 1.0
    for f in reversed(factors):
        running *= f
        cdfs.insert(0, running)
    return cdfs

def project_ultimate(cum, factors):
    n_ap, n_dp = cum.shape
    completed = cum.copy().astype(float)
    for i in range(n_ap):
        last_obs = -1
        for j in range(n_dp - 1, -1, -1):
            if i + j < n_ap and pd.notna(cum.iloc[i, j]):
                last_obs = j
                break
        if last_obs < 0:
            continue
        for j in range(last_obs, n_dp - 1):
            if j < len(factors):
                prev = completed.iloc[i, j]
                completed.iloc[i, j + 1] = prev * factors[j] if pd.notna(prev) and prev > 0 else 0.0
    return completed


# =============================================================================
#  5. INFLATION HELPERS
# =============================================================================

def deflate_triangle_to_real(inc, cum_inflation, n_periods):
    valuation_idx = n_periods - 1
    if len(cum_inflation) <= valuation_idx:
        cum_inflation = np.append(cum_inflation, [cum_inflation[-1]] * (valuation_idx - len(cum_inflation) + 1))
    inf_val = cum_inflation[valuation_idx]
    real_inc = inc.copy().astype(float)
    for ap in inc.index:
        for dp in inc.columns:
            if ap + dp >= n_periods:
                continue
            val = inc.loc[ap, dp]
            if pd.isna(val):
                continue
            t = ap + dp
            inf_t = cum_inflation[min(t, len(cum_inflation) - 1)]
            real_inc.loc[ap, dp] = val * (inf_val / inf_t) if inf_t > 0 else val
    real_cum = real_inc.copy()
    for ap in real_inc.index:
        has_obs = any(pd.notna(real_inc.loc[ap, dp]) for dp in real_inc.columns if ap + dp < n_periods)
        if not has_obs:
            real_cum.loc[ap] = np.nan
            continue
        running = 0.0
        for dp in sorted(real_inc.columns):
            if ap + dp < n_periods:
                v = real_inc.loc[ap, dp]
                running += v if pd.notna(v) else 0.0
                real_cum.loc[ap, dp] = running
            else:
                real_cum.loc[ap, dp] = np.nan
    return real_inc, real_cum

def reinflate_ibnr_per_ap(completed_real, cum_triangle_real, n_periods, per_period_rates):
    valuation_idx = n_periods - 1
    last_rate = per_period_rates[-1] if len(per_period_rates) > 0 else 0.0

    def forward_inflation(t_future):
        factor = 1.0
        for k in range(valuation_idx + 1, t_future + 1):
            ki = k - valuation_idx - 1
            r = per_period_rates[ki] if ki < len(per_period_rates) else last_rate
            factor *= (1.0 + r)
        return factor

    nominal_by_ap = {}
    dp_cols = sorted(completed_real.columns)
    for ap in completed_real.index:
        last_obs = -1
        for dp in sorted(cum_triangle_real.columns, reverse=True):
            if ap + dp < n_periods and pd.notna(cum_triangle_real.loc[ap, dp]):
                last_obs = dp
                break
        if last_obs < 0:
            nominal_by_ap[ap] = 0.0
            continue
        total = 0.0
        for idx_dp, dp in enumerate(dp_cols):
            if dp <= last_obs:
                continue
            if ap + dp >= 2 * n_periods:
                break
            cum_curr = completed_real.loc[ap, dp]
            if pd.isna(cum_curr):
                continue
            cum_prev = completed_real.loc[ap, dp_cols[idx_dp - 1]] if idx_dp > 0 else 0.0
            inc_real = max(float(cum_curr) - float(cum_prev if pd.notna(cum_prev) else 0.0), 0.0)
            if inc_real <= 0.0:
                continue
            total += inc_real * forward_inflation(ap + dp)
        nominal_by_ap[ap] = total
    return nominal_by_ap


# =============================================================================
#  6. DISCOUNTING HELPERS
# =============================================================================

def discount_completed_triangle(completed_triangle, cum_triangle, n_periods, grain, spot_rates=None, flat_rate=None):
    ppy = periods_per_year(grain)
    dp_cols = sorted(completed_triangle.columns)
    total_nominal = 0.0
    total_discounted = 0.0

    for ap in completed_triangle.index:
        last_obs = -1
        for dp in sorted(cum_triangle.columns, reverse=True):
            if ap + dp < n_periods:
                val = cum_triangle.loc[ap, dp]
                if pd.notna(val) and val > 0:
                    last_obs = dp
                    break
        if last_obs < 0 or last_obs >= max(dp_cols):
            continue
        for idx_dp, dp in enumerate(dp_cols):
            if dp <= last_obs:
                continue
            cum_curr = completed_triangle.loc[ap, dp]
            if pd.isna(cum_curr):
                continue
            cum_prev = completed_triangle.loc[ap, dp_cols[idx_dp - 1]] if idx_dp > 0 else 0.0
            inc_payment = max(float(cum_curr) - float(cum_prev if pd.notna(cum_prev) else 0.0), 0.0)
            if inc_payment <= 0.0:
                continue
            periods_ahead = dp - last_obs
            years_ahead = periods_ahead / ppy
            if spot_rates is not None:
                idx = min(int(periods_ahead) - 1, len(spot_rates) - 1)
                r = float(spot_rates[max(idx, 0)])
            else:
                r = float(flat_rate)
            df_factor = 1.0 / (1.0 + r) ** years_ahead
            total_nominal += inc_payment
            total_discounted += inc_payment * df_factor
    return total_nominal, total_discounted
