# -*- coding: utf-8 -*-
"""bootstrap_ra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-GxG7Nb7rNgxLhmLDvjGw_R0rHS9vtQ
"""

# =============================================================================
#  BOOTSTRAP RISK ADJUSTMENT ENGINE
#  England & Verrall (2002) ODP Bootstrap Methodology
#  Tail factor hardcoded to 1.000 (fully developed)
# =============================================================================

import pandas as pd
import numpy as np
from scipy import interpolate

# =============================================================================
#  PERIOD & TRIANGLE HELPERS
# =============================================================================

def periods_per_year(grain):
    return {"Y": 1, "H": 2, "Q": 4, "M": 12}[grain]

def period_index(dt, origin, grain):
    if grain == "Y": return dt.year - origin.year
    elif grain == "H":
        oy = origin.year * 2 + (0 if origin.month <= 6 else 1)
        dy = dt.year * 2 + (0 if dt.month <= 6 else 1)
        return dy - oy
    elif grain == "Q":
        oq = origin.year * 4 + (origin.month - 1) // 3
        dq = dt.year * 4 + (dt.month - 1) // 3
        return dq - oq
    elif grain == "M":
        return (dt.year - origin.year) * 12 + (dt.month - origin.month)

def period_label(idx, origin, grain):
    if grain == "Y": return str(origin.year + idx)
    elif grain == "H":
        base = origin.year * 2 + (0 if origin.month <= 6 else 1) + idx
        y, h = base // 2, base % 2 + 1
        return f"{y}-H{h}"
    elif grain == "Q":
        base = origin.year * 4 + (origin.month - 1) // 3 + idx
        y, q = base // 4, base % 4 + 1
        return f"{y}-Q{q}"
    elif grain == "M":
        total = origin.year * 12 + origin.month - 1 + idx
        y, m = total // 12, total % 12 + 1
        return f"{y}-{m:02d}"


def build_triangles(df, loss_col, report_col, amount_col, origin, grain, n_periods):
    """
    Builds the incremental and cumulative claims triangle from claim-level data.
    Returns inc, cum, and obs_mask (which cells were actually observed).
    """
    df = df.copy()
    df["__ap"] = df[loss_col].apply(lambda d: period_index(d, origin, grain))
    df["__dp"] = df.apply(
        lambda r: max(0, min(period_index(r[report_col], origin, grain) - period_index(r[loss_col], origin, grain), n_periods - 1)),
        axis=1
    )
    df = df[(df["__ap"] >= 0) & (df["__ap"] < n_periods)]
    df_valid = df.dropna(subset=[amount_col])

    if len(df_valid) > 0:
        pivot = df_valid.pivot_table(index="__ap", columns="__dp", values=amount_col, aggfunc="sum")
    else:
        pivot = pd.DataFrame(index=pd.RangeIndex(n_periods), columns=pd.RangeIndex(n_periods), dtype=float)

    for ap in range(n_periods):
        if ap not in pivot.index: pivot.loc[ap] = np.nan
    for dp in range(n_periods):
        if dp not in pivot.columns: pivot[dp] = np.nan

    inc = pivot.sort_index()[sorted(pivot.columns)].copy().astype(float)
    obs_mask = pd.DataFrame(False, index=inc.index, columns=inc.columns)
    for ap in inc.index:
        for dp in inc.columns:
            if ap + dp < n_periods:
                obs_mask.loc[ap, dp] = pd.notna(inc.loc[ap, dp])

    for ap in inc.index:
        for dp in inc.columns:
            if ap + dp >= n_periods: inc.loc[ap, dp] = np.nan

    cum = inc.copy()
    for ap in inc.index:
        has_obs = any(pd.notna(inc.loc[ap, dp]) for dp in inc.columns if ap + dp < n_periods)
        if not has_obs:
            cum.loc[ap] = np.nan
            continue
        running = 0.0
        for dp in sorted(inc.columns):
            if ap + dp < n_periods:
                v = inc.loc[ap, dp]
                running += v if pd.notna(v) else 0.0
                cum.loc[ap, dp] = running
            else:
                cum.loc[ap, dp] = np.nan
    return inc, cum, obs_mask


# =============================================================================
#  CHAIN LADDER HELPERS
# =============================================================================

def volume_weighted_factors(cum, obs_mask=None):
    n_ap, n_dp = cum.shape
    factors = []
    for j in range(n_dp - 1):
        num, den = 0.0, 0.0
        for i in range(n_ap):
            if i + j + 1 < n_ap:
                if obs_mask is not None:
                    if not obs_mask.iloc[i, j] or not obs_mask.iloc[i, j + 1]:
                        continue
                c = cum.iloc[i, j]
                n = cum.iloc[i, j + 1]
                if pd.notna(c) and pd.notna(n) and c > 0:
                    num += n
                    den += c
        factors.append(num / den if den > 0 else 1.0)
    return factors

def compute_cdfs(factors):
    cdfs = []
    running = 1.0
    for f in reversed(factors):
        running *= f
        cdfs.insert(0, running)
    return cdfs

def project_ultimate(cum, factors):
    n_ap, n_dp = cum.shape
    completed = cum.copy().astype(float)
    for i in range(n_ap):
        last_obs = -1
        for j in range(n_dp - 1, -1, -1):
            if i + j < n_ap and pd.notna(cum.iloc[i, j]):
                last_obs = j
                break
        if last_obs < 0:
            continue
        for j in range(last_obs, n_dp - 1):
            if j < len(factors):
                prev = completed.iloc[i, j]
                completed.iloc[i, j + 1] = prev * factors[j] if pd.notna(prev) and prev > 0 else 0.0
    return completed

def run_chain_ladder(cum, factors, origin, grain):
    n_ap, n_dp = cum.shape
    completed = project_ultimate(cum, factors)
    cdfs = compute_cdfs(factors)
    rows = []
    for i in range(n_ap):
        last_obs = -1
        for j in range(n_dp - 1, -1, -1):
            if i + j < n_ap and pd.notna(cum.iloc[i, j]):
                last_obs = j
                break
        if last_obs < 0:
            continue
        current = cum.iloc[i, last_obs]
        ultimate = completed.iloc[i, n_dp - 1]
        ibnr = max(ultimate - current, 0.0)
        cdf = cdfs[last_obs] if last_obs < len(cdfs) else 1.0
        rows.append({
            "Accident_Period": i,
            "Accident_Period_Label": period_label(i, origin, grain),
            "Periods_Developed": last_obs,
            "CDF_to_Ultimate": cdf,
            "Current_Claims": current,
            "Ultimate_Claims": ultimate,
            "IBNR": ibnr
        })
    return pd.DataFrame(rows), completed


# =============================================================================
#  INFLATION HELPERS
# =============================================================================

def deflate_triangle_to_real(inc, cum_inflation, n_periods):
    valuation_idx = n_periods - 1
    if len(cum_inflation) <= valuation_idx:
        cum_inflation = np.append(cum_inflation, [cum_inflation[-1]] * (valuation_idx - len(cum_inflation) + 1))
    inf_val = cum_inflation[valuation_idx]
    real_inc = inc.copy().astype(float)
    for ap in inc.index:
        for dp in inc.columns:
            if ap + dp >= n_periods:
                continue
            val = inc.loc[ap, dp]
            if pd.isna(val):
                continue
            t = ap + dp
            inf_t = cum_inflation[min(t, len(cum_inflation) - 1)]
            real_inc.loc[ap, dp] = val * (inf_val / inf_t) if inf_t > 0 else val
    real_cum = real_inc.copy()
    for ap in real_inc.index:
        has_obs = any(pd.notna(real_inc.loc[ap, dp]) for dp in real_inc.columns if ap + dp < n_periods)
        if not has_obs:
            real_cum.loc[ap] = np.nan
            continue
        running = 0.0
        for dp in sorted(real_inc.columns):
            if ap + dp < n_periods:
                v = real_inc.loc[ap, dp]
                running += v if pd.notna(v) else 0.0
                real_cum.loc[ap, dp] = running
            else:
                real_cum.loc[ap, dp] = np.nan
    return real_inc, real_cum

def reinflate_ibnr_per_ap(completed_real, cum_triangle_real, n_periods, per_period_rates):
    valuation_idx = n_periods - 1
    last_rate = per_period_rates[-1] if len(per_period_rates) > 0 else 0.0

    def forward_inflation(t_future):
        factor = 1.0
        for k in range(valuation_idx + 1, t_future + 1):
            ki = k - valuation_idx - 1
            r = per_period_rates[ki] if ki < len(per_period_rates) else last_rate
            factor *= (1.0 + r)
        return factor

    nominal_by_ap = {}
    dp_cols = sorted(completed_real.columns)
    for ap in completed_real.index:
        last_obs = -1
        for dp in sorted(cum_triangle_real.columns, reverse=True):
            if ap + dp < n_periods and pd.notna(cum_triangle_real.loc[ap, dp]):
                last_obs = dp
                break
        if last_obs < 0:
            nominal_by_ap[ap] = 0.0
            continue
        total = 0.0
        for idx_dp, dp in enumerate(dp_cols):
            if dp <= last_obs:
                continue
            if ap + dp >= 2 * n_periods:
                break
            cum_curr = completed_real.loc[ap, dp]
            if pd.isna(cum_curr):
                continue
            cum_prev = completed_real.loc[ap, dp_cols[idx_dp - 1]] if idx_dp > 0 else 0.0
            inc_real = max(float(cum_curr) - float(cum_prev if pd.notna(cum_prev) else 0.0), 0.0)
            if inc_real <= 0.0:
                continue
            total += inc_real * forward_inflation(ap + dp)
        nominal_by_ap[ap] = total
    return nominal_by_ap


# =============================================================================
#  DISCOUNTING HELPERS
# =============================================================================

def discount_completed_triangle(completed_triangle, cum_triangle, n_periods, grain, spot_rates=None, flat_rate=None):
    ppy = periods_per_year(grain)
    dp_cols = sorted(completed_triangle.columns)
    total_nominal = 0.0
    total_discounted = 0.0

    for ap in completed_triangle.index:
        last_obs = -1
        for dp in sorted(cum_triangle.columns, reverse=True):
            if ap + dp < n_periods:
                val = cum_triangle.loc[ap, dp]
                if pd.notna(val) and val > 0:
                    last_obs = dp
                    break
        if last_obs < 0 or last_obs >= max(dp_cols):
            continue
        for idx_dp, dp in enumerate(dp_cols):
            if dp <= last_obs:
                continue
            cum_curr = completed_triangle.loc[ap, dp]
            if pd.isna(cum_curr):
                continue
            cum_prev = completed_triangle.loc[ap, dp_cols[idx_dp - 1]] if idx_dp > 0 else 0.0
            inc_payment = max(float(cum_curr) - float(cum_prev if pd.notna(cum_prev) else 0.0), 0.0)
            if inc_payment <= 0.0:
                continue
            periods_ahead = dp - last_obs
            years_ahead = periods_ahead / ppy
            if spot_rates is not None:
                idx = min(int(periods_ahead) - 1, len(spot_rates) - 1)
                r = float(spot_rates[max(idx, 0)])
            else:
                r = float(flat_rate)
            df_factor = 1.0 / (1.0 + r) ** years_ahead
            total_nominal += inc_payment
            total_discounted += inc_payment * df_factor
    return total_nominal, total_discounted


# =============================================================================
#  CORE BOOTSTRAP ENGINE
# =============================================================================

def bootstrap_chain_ladder(working_cum, obs_mask, origin, grain, n_periods,
                           n_iterations, add_process_variance,
                           use_inflation, per_period_rates, cum_inflation,
                           use_discounting, spot_rates, flat_rate, seed=None):
    """
    Runs the ODP Bootstrap (England & Verrall, 2002) simulation.
    Returns a dictionary containing the distribution, statistics, and percentiles.
    """
    if seed is not None:
        np.random.seed(seed)

    n_ay, n_dp = working_cum.shape
    cum_filled = working_cum.fillna(0)

    # Step 1: Deterministic Chain Ladder
    factors = volume_weighted_factors(working_cum, obs_mask)
    completed_det = project_ultimate(cum_filled, factors)

    # Step 2: Fit increments and calculate residuals
    fitted_inc = completed_det.copy()
    for i in range(n_ay):
        for j in range(n_dp - 1, 0, -1):
            fitted_inc.iloc[i, j] = completed_det.iloc[i, j] - completed_det.iloc[i, j - 1]

    residuals_list = []
    for i in range(n_ay):
        for j in range(n_dp):
            if i + j < n_ay and obs_mask.iloc[i, j]:
                actual = (cum_filled.iloc[i, j] - cum_filled.iloc[i, j - 1] if j > 0 else cum_filled.iloc[i, j])
                fitted = fitted_inc.iloc[i, j]
                resid = (actual - fitted) / np.sqrt(abs(fitted)) if fitted > 0 else 0.0
                residuals_list.append(resid)

    residuals = np.array(residuals_list)
    n_obs = len(residuals)
    n_params = n_dp - 1
    dof = max(n_obs - n_params, 1)
    phi_raw = np.sum(residuals ** 2) / dof
    PHI_MIN = 0.01
    phi = PHI_MIN if phi_raw < PHI_MIN else phi_raw

    # Step 3: Bootstrap Simulation
    ibnr_nominal_samples = []
    ibnr_discounted_samples = []

    for iteration in range(n_iterations):
        # 3a. Resample residuals and construct pseudo-data
        sampled = np.random.choice(residuals, size=n_obs, replace=True)
        pseudo_inc = fitted_inc.copy().astype(float)
        idx = 0
        for i in range(n_ay):
            for j in range(n_dp):
                if i + j < n_ay and obs_mask.iloc[i, j]:
                    fv = fitted_inc.iloc[i, j]
                    pv = fv + sampled[idx] * np.sqrt(max(abs(fv), 0.001))
                    pseudo_inc.iloc[i, j] = max(pv, 0.0)
                    idx += 1

        pseudo_cum = pseudo_inc.cumsum(axis=1)
        pseudo_factors = volume_weighted_factors(pseudo_cum, obs_mask)
        pseudo_completed = project_ultimate(pseudo_cum, pseudo_factors)

        # 3b. Apply process variance (Gamma ODP) if enabled
        if add_process_variance and phi > 1e-10:
            proc_inc = pseudo_completed.copy()
            for i in range(n_ay):
                for j in range(n_dp - 1, 0, -1):
                    proc_inc.iloc[i, j] = pseudo_completed.iloc[i, j] - pseudo_completed.iloc[i, j - 1]
            for i in range(n_ay):
                for j in range(n_dp):
                    is_future = (i + j >= n_ay) or (not obs_mask.iloc[i, j])
                    if is_future:
                        mean_val = proc_inc.iloc[i, j]
                        if pd.notna(mean_val) and mean_val > 0:
                            shape = mean_val / phi
                            scale = phi
                            proc_inc.iloc[i, j] = max(np.random.gamma(shape, scale), 0.0)
                        else:
                            proc_inc.iloc[i, j] = 0.0
            pseudo_completed = proc_inc.copy()
            for i in range(n_ay):
                running = 0.0
                for j in range(n_dp):
                    v = proc_inc.iloc[i, j]
                    running += v if pd.notna(v) and v > 0 else 0.0
                    pseudo_completed.iloc[i, j] = running

        # 3c. Calculate IBNR for this iteration
        ibnr_working = 0.0
        for i in range(n_ay):
            last_obs = -1
            for j in range(n_dp - 1, -1, -1):
                if i + j < n_ay and obs_mask.iloc[i, j]:
                    last_obs = j
                    break
            if last_obs >= 0:
                current = pseudo_cum.iloc[i, last_obs]
                ultimate = pseudo_completed.iloc[i, n_dp - 1]
                ibnr_working += max(ultimate - current, 0.0)

        # 3d. Apply Inflation (if enabled)
        if use_inflation and per_period_rates is not None:
            nominal_map = reinflate_ibnr_per_ap(pseudo_completed, pseudo_cum, n_periods, per_period_rates)
            ibnr_nominal_this = sum(nominal_map.values())
        else:
            ibnr_nominal_this = ibnr_working
        ibnr_nominal_samples.append(ibnr_nominal_this)

        # 3e. Apply Discounting (if enabled)
        if use_discounting:
            if use_inflation and per_period_rates is not None:
                valuation_idx = n_periods - 1
                last_rate = per_period_rates[-1] if len(per_period_rates) > 0 else 0.0
                nom_completed = pseudo_completed.copy().astype(float)
                dp_cols = sorted(pseudo_completed.columns)
                for i in range(n_ay):
                    last_obs = -1
                    for j in range(n_dp - 1, -1, -1):
                        if i + j < n_ay and obs_mask.iloc[i, j]:
                            last_obs = j
                            break
                    for dp_idx, dp in enumerate(dp_cols):
                        if dp <= last_obs:
                            continue
                        t_future = i + dp
                        factor = 1.0
                        for k in range(valuation_idx + 1, t_future + 1):
                            ki = k - valuation_idx - 1
                            r = per_period_rates[ki] if ki < len(per_period_rates) else last_rate
                            factor *= (1.0 + r)
                        v = pseudo_completed.iloc[i, dp_idx]
                        nom_completed.iloc[i, dp_idx] = v * factor if pd.notna(v) else np.nan
                disc_tri = nom_completed
            else:
                disc_tri = pseudo_completed

            _, total_disc = discount_completed_triangle(disc_tri, pseudo_cum, n_periods, grain, spot_rates, flat_rate)
            ibnr_discounted_samples.append(total_disc)

    # Step 4: Compile Results
    ibnr_nominal_arr = np.array(ibnr_nominal_samples)
    ibnr_discounted_arr = np.array(ibnr_discounted_samples) if ibnr_discounted_samples else None

    cl_df, cl_completed = run_chain_ladder(cum_filled, factors, origin, grain)
    cl_ibnr_working = cl_df["IBNR"].sum()
    if use_inflation and per_period_rates is not None:
        nom_map = reinflate_ibnr_per_ap(cl_completed, working_cum, n_periods, per_period_rates)
        cl_ibnr_nominal = sum(nom_map.values())
    else:
        cl_ibnr_nominal = cl_ibnr_working

    results = {
        "cl_ibnr_nominal": cl_ibnr_nominal,
        "bootstrap_mean": float(np.mean(ibnr_nominal_arr)),
        "bootstrap_median": float(np.median(ibnr_nominal_arr)),
        "bootstrap_std": float(np.std(ibnr_nominal_arr, ddof=1)),
        "bootstrap_cv": (float(np.std(ibnr_nominal_arr, ddof=1) / np.mean(ibnr_nominal_arr)) if np.mean(ibnr_nominal_arr) > 0 else 0.0),
        "phi": float(phi),
        "phi_raw": float(phi_raw),
        "process_variance": add_process_variance,
        "ibnr_nominal_samples": ibnr_nominal_arr,
        "ibnr_discounted_samples": ibnr_discounted_arr,
        "dev_factors": factors,
        "residuals": residuals,
        "n_iterations": n_iterations,
        "percentiles_nominal": {},
        "percentiles_discounted": {},
    }
    for p in [50, 70, 75, 80, 85, 90, 95, 99, 99.5]:
        results["percentiles_nominal"][p] = float(np.percentile(ibnr_nominal_arr, p))
        if ibnr_discounted_arr is not None:
            results["percentiles_discounted"][p] = float(np.percentile(ibnr_discounted_arr, p))

    return results


def calculate_risk_adjustment(boot_results, confidence_level, ra_base):
    """
    Calculates the Risk Adjustment (RA) based on the bootstrap results.
    """
    base = boot_results["cl_ibnr_nominal"] if ra_base == "cl" else boot_results["bootstrap_mean"]
    pctl = boot_results["percentiles_nominal"].get(confidence_level, base)
    ra = max(pctl - base, 0.0)
    return {
        "confidence_level": confidence_level,
        "ra_base": ra_base,
        "base_ibnr": base,
        "percentile_ibnr": pctl,
        "risk_adjustment": ra
    }
