# -*- coding: utf-8 -*-
"""mack_ra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ykGGazG7qPIryeBbLee9MfaSzi-X2Fw
"""

# =============================================================================
#  MACK CHAIN LADDER RISK ADJUSTMENT ENGINE
#  Mack (1993) Standard Error Methodology
#  Tail factor hardcoded to 1.000 (fully developed)
# =============================================================================

import pandas as pd
import numpy as np
from scipy import stats

# =============================================================================
#  PERIOD & TRIANGLE HELPERS (Same as IBNR engines)
# =============================================================================

def periods_per_year(grain):
    return {"Y": 1, "H": 2, "Q": 4, "M": 12}[grain]

def period_index(dt, origin, grain):
    if grain == "Y": return dt.year - origin.year
    elif grain == "H":
        oy = origin.year * 2 + (0 if origin.month <= 6 else 1)
        dy = dt.year * 2 + (0 if dt.month <= 6 else 1)
        return dy - oy
    elif grain == "Q":
        oq = origin.year * 4 + (origin.month - 1) // 3
        dq = dt.year * 4 + (dt.month - 1) // 3
        return dq - oq
    elif grain == "M":
        return (dt.year - origin.year) * 12 + (dt.month - origin.month)

def period_label(idx, origin, grain):
    if grain == "Y": return str(origin.year + idx)
    elif grain == "H":
        base = origin.year * 2 + (0 if origin.month <= 6 else 1) + idx
        y, h = base // 2, base % 2 + 1
        return f"{y}-H{h}"
    elif grain == "Q":
        base = origin.year * 4 + (origin.month - 1) // 3 + idx
        y, q = base // 4, base % 4 + 1
        return f"{y}-Q{q}"
    elif grain == "M":
        total = origin.year * 12 + origin.month - 1 + idx
        y, m = total // 12, total % 12 + 1
        return f"{y}-{m:02d}"


def build_triangles(df, loss_col, report_col, amount_col, origin, grain, n_periods):
    """
    Builds the cumulative claims triangle from claim-level data.
    Returns the cumulative triangle and the observed mask.
    """
    df = df.copy()
    df["__ap"] = df[loss_col].apply(lambda d: period_index(d, origin, grain))
    df["__dp"] = df.apply(
        lambda r: max(0, min(period_index(r[report_col], origin, grain) - period_index(r[loss_col], origin, grain), n_periods - 1)),
        axis=1
    )
    df = df[(df["__ap"] >= 0) & (df["__ap"] < n_periods)]
    df_valid = df.dropna(subset=[amount_col])

    if len(df_valid) > 0:
        pivot = df_valid.pivot_table(index="__ap", columns="__dp", values=amount_col, aggfunc="sum")
    else:
        pivot = pd.DataFrame(index=pd.RangeIndex(n_periods), columns=pd.RangeIndex(n_periods), dtype=float)

    for ap in range(n_periods):
        if ap not in pivot.index: pivot.loc[ap] = np.nan
    for dp in range(n_periods):
        if dp not in pivot.columns: pivot[dp] = np.nan

    inc = pivot.sort_index()[sorted(pivot.columns)].copy().astype(float)

    obs_mask = pd.DataFrame(False, index=inc.index, columns=inc.columns)
    for ap in inc.index:
        for dp in inc.columns:
            if ap + dp < n_periods:
                obs_mask.loc[ap, dp] = pd.notna(inc.loc[ap, dp])

    for ap in inc.index:
        for dp in inc.columns:
            if ap + dp >= n_periods: inc.loc[ap, dp] = np.nan

    cum = inc.copy()
    for ap in inc.index:
        has_obs = any(pd.notna(inc.loc[ap, dp]) for dp in inc.columns if ap + dp < n_periods)
        if not has_obs:
            cum.loc[ap] = np.nan
            continue
        running = 0.0
        for dp in sorted(inc.columns):
            if ap + dp < n_periods:
                v = inc.loc[ap, dp]
                running += v if pd.notna(v) else 0.0
                cum.loc[ap, dp] = running
            else:
                cum.loc[ap, dp] = np.nan
    return cum, obs_mask


def volume_weighted_factors(cum, obs_mask):
    n_ap, n_dp = cum.shape
    factors = []
    S = {}
    # Calculate column sums (observed only)
    for j in range(n_dp):
        col_sum = 0
        for i in range(n_ap):
            if obs_mask.iloc[i, j] and pd.notna(cum.iloc[i, j]):
                col_sum += cum.iloc[i, j]
        S[j] = col_sum

    for j in range(n_dp - 1):
        num, den = 0.0, 0.0
        for i in range(n_ap):
            if i + j + 1 < n_ap and obs_mask.iloc[i, j] and obs_mask.iloc[i, j + 1]:
                c = cum.iloc[i, j]
                n = cum.iloc[i, j + 1]
                if pd.notna(c) and pd.notna(n) and c > 0:
                    num += n
                    den += c
        factors.append(num / den if den > 0 else 1.0)
    return factors, S


# =============================================================================
#  CORE MACK ENGINE
# =============================================================================

def calculate_mack_chain_ladder(cum_triangle, obs_mask, confidence_level=0.995):
    """
    Calculate Mack Chain Ladder standard errors and Risk Adjustment.
    """
    # Convert to numpy for speed
    triangle_values = cum_triangle.values
    n_ay, n_dev = triangle_values.shape

    # Step 1: Calculate Development Factors & Column Sums
    dev_factors, S = volume_weighted_factors(cum_triangle, obs_mask)

    # Step 2: Calculate Sigma^2 (Process Variance)
    sigma2 = {}
    for j in range(n_dev - 1):
        factors = []
        weights = []
        for i in range(n_ay):
            if obs_mask.iloc[i, j] and obs_mask.iloc[i, j + 1] and cum_triangle.iloc[i, j] > 0:
                factor = cum_triangle.iloc[i, j + 1] / cum_triangle.iloc[i, j]
                factors.append(factor)
                weights.append(cum_triangle.iloc[i, j])
        if len(factors) > 1 and j < len(dev_factors):
            f_j = dev_factors[j]
            weighted_sq_sum = sum(w * (f - f_j) ** 2 for f, w in zip(factors, weights))
            sigma2[j] = weighted_sq_sum / (len(factors) - 1)
        else:
            sigma2[j] = 0

    # Mack's extrapolation for the last period
    non_zero_sigma = [(j, val) for j, val in sigma2.items() if val > 0]
    if len(non_zero_sigma) >= 2:
        last_j, last_val = non_zero_sigma[-1]
        second_j, second_val = non_zero_sigma[-2]
        option1 = (last_val ** 4) / (second_val ** 3) if second_val > 0 else 0
        option2 = last_val ** 2
        option3 = second_val ** 2
        sigma2[n_dev - 1] = min(option1, option2, option3)
    else:
        sigma2[n_dev - 1] = sigma2.get(n_dev - 2, 0)

    # Step 3: Project Ultimate Triangle
    completed = cum_triangle.copy().astype(float)
    for i in range(n_ay):
        last_obs = -1
        for j in range(n_dev - 1, -1, -1):
            if obs_mask.iloc[i, j] and pd.notna(cum_triangle.iloc[i, j]):
                last_obs = j
                break
        if last_obs < 0: continue
        for j in range(last_obs, n_dev - 1):
            if j < len(dev_factors):
                prev = completed.iloc[i, j]
                completed.iloc[i, j + 1] = prev * dev_factors[j] if pd.notna(prev) and prev > 0 else 0.0

    # Step 4: Calculate IBNR and Variance per Accident Period
    results = []
    total_ibnr = 0
    total_variance = 0

    for i in range(n_ay):
        last_obs = -1
        for j in range(n_dev - 1, -1, -1):
            if obs_mask.iloc[i, j] and pd.notna(cum_triangle.iloc[i, j]):
                last_obs = j
                break

        ultimate = completed.iloc[i, n_dev - 1]
        current = cum_triangle.iloc[i, last_obs] if last_obs >= 0 else 0
        ibnr = ultimate - current

        variance = 0
        if last_obs < n_dev - 1 and last_obs >= 0 and ibnr > 0:
            total_sum = 0
            for k in range(last_obs, n_dev - 1):
                C_ik = cum_triangle.iloc[i, k]
                if C_ik > 0 and k in sigma2 and sigma2[k] > 0 and k < len(dev_factors):
                    f_k = dev_factors[k]
                    term_a = sigma2[k] / (f_k ** 2 * C_ik)
                    term_b = sigma2[k] / (f_k ** 2 * S.get(k, 1))
                    total_sum += term_a + term_b
            variance = (ultimate ** 2) * total_sum

        total_ibnr += ibnr
        total_variance += variance

        results.append({
            'accident_period': i,
            'accident_period_label': period_label(i, cum_triangle.index[0], 'Y'), # Simplified label
            'current': current,
            'ultimate': ultimate,
            'ibnr': ibnr,
            'variance': variance,
            'std_error': np.sqrt(variance) if variance > 0 else 0
        })

    results_df = pd.DataFrame(results)

    # Step 5: Risk Adjustment
    total_se = np.sqrt(total_variance)
    z_score = stats.norm.ppf(confidence_level)
    risk_adjustment = total_se * z_score
    lic = total_ibnr + risk_adjustment

    return {
        'ibnr_by_ay': results_df[['accident_period', 'accident_period_label', 'ibnr', 'std_error']].copy(),
        'total_ibnr': total_ibnr,
        'total_se': total_se,
        'total_variance': total_variance,
        'risk_adjustment': risk_adjustment,
        'lic': lic,
        'dev_factors': dev_factors,
        'sigma2': sigma2,
        'results_df': results_df,
        'z_score': z_score
    }