# -*- coding: utf-8 -*-
"""bcl_ibnr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDLr_8yCv5ICJIq5TE7WGqpegaew8cvG
"""

# =============================================================================
#  BASIC CHAIN LADDER (BCL) IBNR ENGINE
#  Volume-Weighted LDFs, tail factor hardcoded to 1.000
# =============================================================================

import pandas as pd
import numpy as np


def periods_per_year(grain):
    return {"Y": 1, "H": 2, "Q": 4, "M": 12}[grain]


def period_label(idx, origin, grain):
    if grain == "Y":
        return str(origin.year + idx)
    elif grain == "H":
        base = origin.year * 2 + (0 if origin.month <= 6 else 1) + idx
        y, h = base // 2, base % 2 + 1
        return f"{y}-H{h}"
    elif grain == "Q":
        base = origin.year * 4 + (origin.month - 1) // 3 + idx
        y, q = base // 4, base % 4 + 1
        return f"{y}-Q{q}"
    elif grain == "M":
        total = origin.year * 12 + origin.month - 1 + idx
        y, m = total // 12, total % 12 + 1
        return f"{y}-{m:02d}"


def volume_weighted_factors(cum):
    n_ap, n_dp = cum.shape
    factors = []
    for j in range(n_dp - 1):
        num, den = 0.0, 0.0
        for i in range(n_ap):
            if i + j + 1 < n_ap:
                c = cum.iloc[i, j]
                n = cum.iloc[i, j + 1]
                if c > 0:
                    num += n
                    den += c
        factors.append(num / den if den > 0 else 1.0)
    return factors


def project_ultimate(cum, factors):
    n_ap, n_dp = cum.shape
    completed = cum.copy().astype(float)
    for i in range(n_ap):
        last_obs = -1
        for j in range(n_dp - 1, -1, -1):
            if i + j < n_ap:
                last_obs = j
                break
        if last_obs < 0:
            continue
        for j in range(last_obs, n_dp - 1):
            if j < len(factors):
                prev = completed.iloc[i, j]
                completed.iloc[i, j + 1] = prev * factors[j] if prev > 0 else 0.0
    return completed


def calculate_bcl_ibnr(cum_triangle, start_date, period_unit):
    """
    Calculate BCL IBNR. Tail factor = 1.000 (fully developed).
    """
    n_ap, n_dp = cum_triangle.shape
    factors = volume_weighted_factors(cum_triangle)
    completed = project_ultimate(cum_triangle, factors)

    rows = []
    total_ibnr = 0.0

    for i in range(n_ap):
        last_obs = -1
        for j in range(n_dp - 1, -1, -1):
            if i + j < n_ap:
                last_obs = j
                break
        if last_obs < 0:
            continue

        current = cum_triangle.iloc[i, last_obs]
        ultimate = completed.iloc[i, n_dp - 1]
        ibnr = max(ultimate - current, 0.0)
        total_ibnr += ibnr

        rows.append({
            'Accident_Period': i,
            'Accident_Period_Label': period_label(i, start_date, period_unit),
            'Current_Claims': current,
            'Ultimate_Claims': ultimate,
            'IBNR': ibnr
        })

    return {
        'results_df': pd.DataFrame(rows),
        'total_ibnr': total_ibnr,
        'dev_factors': factors,
        'completed_triangle': completed
    }
