# -*- coding: utf-8 -*-
"""bf_ibnr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1efQJj1_aEAH_H-jDdspGWv7OCDHmLmSq
"""

# =============================================================================
#  BORNHUETTER-FERGUSON IBNR ENGINE
#  Tail factor hardcoded to 1.000 (fully developed)
# =============================================================================

import pandas as pd
import numpy as np


def periods_per_year(grain):
    return {"Y": 1, "H": 2, "Q": 4, "M": 12}[grain]


def period_label(idx, origin, grain):
    if grain == "Y":
        return str(origin.year + idx)
    elif grain == "H":
        base = origin.year * 2 + (0 if origin.month <= 6 else 1) + idx
        y, h = base // 2, base % 2 + 1
        return f"{y}-H{h}"
    elif grain == "Q":
        base = origin.year * 4 + (origin.month - 1) // 3 + idx
        y, q = base // 4, base % 4 + 1
        return f"{y}-Q{q}"
    elif grain == "M":
        total = origin.year * 12 + origin.month - 1 + idx
        y, m = total // 12, total % 12 + 1
        return f"{y}-{m:02d}"


def volume_weighted_factors(cum):
    n_ap, n_dp = cum.shape
    factors = []
    for j in range(n_dp - 1):
        num, den = 0.0, 0.0
        for i in range(n_ap):
            if i + j + 1 < n_ap:
                c = cum.iloc[i, j]
                n = cum.iloc[i, j + 1]
                if c > 0:
                    num += n
                    den += c
        factors.append(num / den if den > 0 else 1.0)
    return factors


def compute_cdfs(factors):
    cdfs = []
    running = 1.0
    for f in reversed(factors):
        running *= f
        cdfs.insert(0, running)
    return cdfs


def calculate_bf_ibnr(cum_triangle, premiums, elr, start_date, period_unit):
    """
    Calculate BF IBNR. Tail factor = 1.000 (fully developed).
    """
    n_ay, n_dev = cum_triangle.shape
    dev_factors = volume_weighted_factors(cum_triangle)
    cdfs = compute_cdfs(dev_factors)
    pct_unpaid = [1 - (1 / cdf) if cdf > 0 else 0 for cdf in cdfs]

    results = []
    total_bf_ibnr = 0.0

    for i in range(n_ay):
        last_obs = -1
        for j in range(n_dev - 1, -1, -1):
            if i + j < n_ay:
                last_obs = j
                break
        if last_obs == -1:
            continue

        current = cum_triangle.iloc[i, last_obs]
        expected_ultimate = premiums[i] * elr

        if last_obs < len(pct_unpaid):
            bf_ibnr = expected_ultimate * pct_unpaid[last_obs]
            pct_dev = (1 - pct_unpaid[last_obs]) * 100
            cdf_val = cdfs[last_obs]
        else:
            bf_ibnr = 0
            pct_dev = 100
            cdf_val = 1.0

        bf_ultimate = current + bf_ibnr
        total_bf_ibnr += bf_ibnr

        results.append({
            'Accident_Period': i,
            'Accident_Period_Label': period_label(i, start_date, period_unit),
            'Current_Claims': current,
            'Premium': premiums[i],
            'ELR': elr,
            'Expected_Ultimate': expected_ultimate,
            'CDF_to_Ultimate': cdf_val,
            'Pct_Developed': pct_dev,
            'BF_IBNR': bf_ibnr,
            'BF_Ultimate': bf_ultimate
        })

    return {
        'results_df': pd.DataFrame(results),
        'total_bf_ibnr': total_bf_ibnr,
        'dev_factors': dev_factors,
        'cdfs': cdfs,
        'pct_unpaid': pct_unpaid
    }