# -*- coding: utf-8 -*-
"""cape_cod_ibnr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/169zHc7l_g-7HW2I3eoTEbd-E-mUZlAPh
"""

# =============================================================================
#  CAPE COD IBNR ENGINE
#  Tail factor hardcoded to 1.000 (fully developed)
# =============================================================================

import pandas as pd
import numpy as np


def periods_per_year(grain):
    return {"Y": 1, "H": 2, "Q": 4, "M": 12}[grain]


def period_label(idx, origin, grain):
    if grain == "Y":
        return str(origin.year + idx)
    elif grain == "H":
        base = origin.year * 2 + (0 if origin.month <= 6 else 1) + idx
        y, h = base // 2, base % 2 + 1
        return f"{y}-H{h}"
    elif grain == "Q":
        base = origin.year * 4 + (origin.month - 1) // 3 + idx
        y, q = base // 4, base % 4 + 1
        return f"{y}-Q{q}"
    elif grain == "M":
        total = origin.year * 12 + origin.month - 1 + idx
        y, m = total // 12, total % 12 + 1
        return f"{y}-{m:02d}"


def volume_weighted_factors(cum):
    n_ap, n_dp = cum.shape
    factors = []
    for j in range(n_dp - 1):
        num, den = 0.0, 0.0
        for i in range(n_ap):
            if i + j + 1 < n_ap:
                c = cum.iloc[i, j]
                n = cum.iloc[i, j + 1]
                if c > 0:
                    num += n
                    den += c
        factors.append(num / den if den > 0 else 1.0)
    return factors


def compute_cdfs(factors):
    cdfs = []
    running = 1.0
    for f in reversed(factors):
        running *= f
        cdfs.insert(0, running)
    return cdfs


def calculate_cape_cod_ibnr(cum_triangle, premiums, start_date, period_unit):
    """
    Calculate Cape Cod IBNR. Tail factor = 1.000 (fully developed).
    """
    n_ay, n_dev = cum_triangle.shape
    dev_factors = volume_weighted_factors(cum_triangle)
    cdfs = compute_cdfs(dev_factors)
    pct_developed = [1 / cdf if cdf > 0 else 1.0 for cdf in cdfs]

    developed_claims = []
    used_up_premiums = []

    for i in range(n_ay):
        last_obs = -1
        for j in range(n_dev - 1, -1, -1):
            if i + j < n_ay:
                last_obs = j
                break
        if last_obs == -1:
            developed_claims.append(0)
            used_up_premiums.append(0)
            continue

        current = cum_triangle.iloc[i, last_obs]
        pct_dev = pct_developed[last_obs] if last_obs < len(pct_developed) else 1.0
        developed_claims.append(current)
        used_up_premiums.append(premiums[i] * pct_dev)

    total_developed = sum(developed_claims)
    total_used_up = sum(used_up_premiums)
    cape_cod_lr = total_developed / total_used_up if total_used_up > 0 else 0

    results = []
    total_cc_ibnr = 0.0

    for i in range(n_ay):
        last_obs = -1
        for j in range(n_dev - 1, -1, -1):
            if i + j < n_ay:
                last_obs = j
                break
        if last_obs == -1:
            continue

        current = cum_triangle.iloc[i, last_obs]
        pct_dev = pct_developed[last_obs] if last_obs < len(pct_developed) else 1.0
        pct_unpaid = 1 - pct_dev
        expected_ultimate = premiums[i] * cape_cod_lr
        cc_ibnr = expected_ultimate * pct_unpaid
        cc_ultimate = current + cc_ibnr
        total_cc_ibnr += cc_ibnr

        results.append({
            'Accident_Period': i,
            'Accident_Period_Label': period_label(i, start_date, period_unit),
            'Current_Claims': current,
            'Premium': premiums[i],
            'Used_Up_Premium': used_up_premiums[i],
            'Pct_Developed': pct_dev * 100,
            'Pct_Unpaid': pct_unpaid * 100,
            'Cape_Cod_LR': cape_cod_lr,
            'Expected_Ultimate': expected_ultimate,
            'Cape_Cod_IBNR': cc_ibnr,
            'Cape_Cod_Ultimate': cc_ultimate
        })

    return {
        'results_df': pd.DataFrame(results),
        'total_cc_ibnr': total_cc_ibnr,
        'cape_cod_lr': cape_cod_lr,
        'total_developed': total_developed,
        'total_used_up': total_used_up,
        'dev_factors': dev_factors,
        'cdfs': cdfs,
        'pct_developed': pct_developed
    }