# -*- coding: utf-8 -*-
"""percentage_ibnr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5GPp7Mh1tKqAfNh19C_Uvbc9pp4R9-0
"""

# =============================================================================
#  IBNR PERCENTAGE METHOD ENGINE
#  Formula: IBNR = Amount × IBNR_Percentage
# =============================================================================

import pandas as pd


def calculate_percentage_ibnr(df, date_col, lob_col, amount_cols, from_date, to_date, ibnr_pct):
    """
    Calculate IBNR using the percentage method.

    Parameters:
    -----------
    df : pd.DataFrame
        The raw data.
    date_col : str
        Column name for the date.
    lob_col : str
        Column name for Line of Business.
    amount_cols : list
        List of column names for numeric amounts.
    from_date : pd.Timestamp
        Start of the period.
    to_date : pd.Timestamp
        End of the period.
    ibnr_pct : float
        The IBNR percentage (e.g., 0.10 for 10%).

    Returns:
    --------
    summary_df : pd.DataFrame
        Grouped summary with IBNR calculated.
    grand_total_ibnr : float
        Total IBNR across all LOBs and amount columns.
    """
    # 1. Filter by Date Range
    mask = (df[date_col] >= from_date) & (df[date_col] <= to_date)
    df_filtered = df[mask].copy()

    # 2. Group by LOB and sum amounts
    summary_df = df_filtered.groupby(lob_col)[amount_cols].sum().reset_index()

    # 3. Calculate IBNR for each amount column
    for col in amount_cols:
        summary_df[f"{col}_IBNR"] = summary_df[col] * ibnr_pct

    # 4. Add a TOTAL row
    total_row = {lob_col: "TOTAL"}
    for col in amount_cols:
        total_row[col] = summary_df[col].sum()
        total_row[f"{col}_IBNR"] = total_row[col] * ibnr_pct

    summary_df = pd.concat([summary_df, pd.DataFrame([total_row])], ignore_index=True)

    # 5. Calculate Grand Total IBNR
    grand_total_ibnr = sum(summary_df[f"{c}_IBNR"].iloc[-1] for c in amount_cols)

    return summary_df, grand_total_ibnr